spring:
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/reactive
    username: postgres
    password: bahmanz
  flyway:
    url: jdbc::postgresql://127.0.0.1:5432/reactive
    user: postgres
    password: bahmanz